version:  "3.9"

services:  
  comix-db:
    image: postgres
    container_name : "comix-db"
    volumes:
      - db-data:/data/db
    hostname: comix-db
    networks:
      - "comix_net"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: comix
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: comix-db 

volumes:
  db-data: 

networks:
  comix_net:
    driver: bridge
